// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "anotherVersion", input: never, result: string } | 
        { key: "products.get", input: string, result: Product } | 
        { key: "version", input: never, result: string },
    mutations: never,
    subscriptions: never
};

export type Product = { id: string; name: string; slug: string; price: ProductPrice; description: string; primary_image: Image | null; secondary_image: Image | null; images: Image[]; availability: ProductAvailability; label: string | null; variants: Variant[] }

export type Image = { picture_sources: PictureSource[]; src: string; srcset: string; alt: string }

export type ProductPrice = { actual: string; compare_at: string | null }

export type Variant = { id: string; slug: string; price: ProductPrice; availability: ProductAvailability; images: Image[]; image: Image | null; size: string | null; color: string | null; material: string | null; style: string | null }

export type PictureSource = { media: string; srcset: string }

export type ProductAvailability = "InStock" | "Limited" | "SoldOut" | "PreOrder"
