import { QueryClient } from '@tanstack/svelte-query';
import { FetchTransport, createClient } from '@rspc/client';

import type { Procedures } from './bindings'; // These are generated by rspc in Rust for you.

const client = createClient<Procedures>({
	transport: new FetchTransport('http://localhost:9000/rspc/1', (input, init) =>
		fetch(input, { ...init, credentials: 'include' }),
	),
});

const queryClient = new QueryClient();

export { client, queryClient };
